global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'microservice'
    static_configs:
      - targets: ['app:5000']  # Replace 'app:5000' with the appropriate service name and port if different
